# Generated by Django 3.0.6 on 2020-09-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('firstname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('native_language', models.CharField(max_length=30)),
                ('also_speaks', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('created_with', models.DateTimeField(auto_now=True)),
                ('intro_video', models.CharField(max_length=11)),
                ('subject_matter', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
